# DVC Pipeline Configuration for IEEE-CIS Fraud Detection
# ========================================================
# Run the pipeline: dvc repro
# Run specific stage: dvc repro data_ingestion
# Visualize pipeline: dvc dag

stages:
  # --------------------------------------------------------
  # Stage 1: Data Ingestion
  # --------------------------------------------------------
  data_ingestion:
    cmd: python -m src.components.data_ingestion --source s3
    deps:
      - src/components/data_ingestion.py
      - src/utils/fetch_data.py
      - config/config.yaml
    outs:
      - artifacts/data/raw/raw_data.csv

    params:
      - config/config.yaml:
          - data_ingestion.source_type

  # --------------------------------------------------------
  # Stage 2: Data Transformation (placeholder)
  # --------------------------------------------------------
  data_transformation_Feature_engineering:
    cmd: python -m src.components.data_FE_transformation
    deps:
      - src/components/data_FE_transformation.py
      - src/components/data_ingestion.py
      - artifacts/data/raw/raw_data.csv
    outs:
      - artifacts/data/transformed/Train_transformed.csv

  # --------------------------------------------------------
  # Stage 3: Feature Engineering (placeholder)
  # --------------------------------------------------------
  # feature_engineering:
  #   cmd: python -m src.features.feature_engineering
  #   deps:
  #     - src/features/feature_engineering.py
  #     - artifacts/data/transformed/train_transformed.csv
  #   outs:
  #     - artifacts/features/train_features.csv

  # --------------------------------------------------------
  # Stage 4: Model Training (placeholder)
  # --------------------------------------------------------
  # model_training:
  #   cmd: python -m src.models.train
  #   deps:
  #     - src/models/train.py
  #     - artifacts/features/train_features.csv
  #   outs:
  #     - artifacts/models/model.pkl
  #   metrics:
  #     - artifacts/metrics/metrics.json:
  #         cache: false

  # --------------------------------------------------------
  # Stage 5: Model Evaluation (placeholder)
  # --------------------------------------------------------
  # model_evaluation:
  #   cmd: python -m src.models.evaluate
  #   deps:
  #     - src/models/evaluate.py
  #     - artifacts/models/model.pkl
  #     - artifacts/features/test_features.csv
  #   metrics:
  #     - artifacts/metrics/evaluation.json:
  #         cache: false
