# DVC Pipeline Configuration for IEEE-CIS Fraud Detection
# ========================================================
# Run the pipeline: dvc repro
# Run specific stage: dvc repro data_ingestion
# Visualize pipeline: dvc dag

stages:
  # --------------------------------------------------------
  # Stage 1: Data Ingestion
  # --------------------------------------------------------
  data_ingestion:
    cmd: python -m src.components.data_ingestion --source s3
    deps:
      - src/components/data_ingestion.py
      - src/utils/fetch_data.py
      - config/config.yaml
      - src/constants/schema.yaml
    outs:
      - artifacts/data/raw/raw_data.csv

    params:
      - config/config.yaml:
          - data_ingestion.source_type

  # --------------------------------------------------------
  # Stage 2: Data Transformation and Feature Engineering
  # --------------------------------------------------------
  data_transformation_Feature_engineering:
    cmd: python -m src.components.data_FE_transformation
    deps:
      - src/components/data_FE_transformation.py
      - src/constants/config.py
      - artifacts/data/raw/raw_data.csv
      - src/constants/schema.yaml
    outs:
      - artifacts/data/transformed/Train_transformed.csv
      - artifacts/data/transformed/Test_transformed.csv



  # --------------------------------------------------------
  # Stage 3: Model Training & Evaluation
  # --------------------------------------------------------
  model_training:
    cmd: python -m src.components.model_training_evaluation
    deps:
      - src/components/model_training_evaluation.py
      - src/constants/config.py
      - src/constants/params.yaml
      - src/constants/schema.yaml
      - artifacts/data/transformed/Train_transformed.csv
      - artifacts/data/transformed/Test_transformed.csv
    params:
      - src/constants/params.yaml:
          - model_params.XGBClassifier
          - model_training
    outs:
      - models/XGBClassifier_latest.joblib
    metrics:
      - models/metrics.json:
          cache: false
    plots:
      - models/confusion_matrix.png:
          cache: false

  # --------------------------------------------------------
  # Stage 5: Model Evaluation (placeholder)
  # --------------------------------------------------------
  # model_evaluation:
  #   cmd: python -m src.models.evaluate
  #   deps:
  #     - src/models/evaluate.py
  #     - artifacts/models/model.pkl
  #     - artifacts/features/test_features.csv
  #   metrics:
  #     - artifacts/metrics/evaluation.json:
  #         cache: false
