metrics:
  test:
    accuracy: 0.9835
    average_precision: 0.6578629807998753
    f1_score: 0.6206896551724138
    false_negatives: 26
    false_positives: 7
    precision: 0.7941176470588235
    recall: 0.5094339622641509
    roc_auc: 0.9177447645628011
    true_negatives: 1940
    true_positives: 27
  train:
    accuracy: 0.999875
    average_precision: 0.9999999999999999
    f1_score: 0.9976470588235294
    false_negatives: 0
    false_positives: 1
    precision: 0.9953051643192489
    recall: 1.0
    roc_auc: 1.0
    true_negatives: 7787
    true_positives: 212
model_name: XGBClassifier
model_path: models/XGBClassifier_v1.joblib
params:
  colsample_bytree: 0.7
  device: cuda
  early_stopping_rounds: 80
  eval_metric: auc
  learning_rate: 0.02
  max_depth: 10
  min_child_weight: 5
  n_estimators: 3000
  objective: binary:logistic
  reg_alpha: 1
  reg_lambda: 2
  scale_pos_weight: 27
  subsample: 0.8
  tree_method: hist
run_id: 72377bc225624fc089ad42c5d7b6e79d
version: 1
